version: '3.3'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4alfonso4
      POSTGRES_DB: bank0
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: